name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
      install-and-test:
        runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x, 14.x, 16.x, 18.x]

      steps:
        - uses: actions/checkout@master

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install packages
          run: yarn install --frozen-lockfile

        - name: Lint
          run: yarn lint

        - name: Test
          run: yarn test

          env:
            CI: true