name: Dependabot Auto Merge

on: 
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto Merge Dependabot PRs
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.AUTO_MERGE_TOKEN }}"

      - name: Approve and Merge PR
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
