name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to S3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy
      run: aws s3 sync ./dist s3://quotes-site
  
  test:
    needs: deploy
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Run Playwright tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: yarn
    
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    
    - name: Run Playwright tests
      run: URL=${{ vars.S3_URL }} yarn playwright test
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1